### ISSUE TITLE
Can't delete user

### ISSUE THREAD

**Issue by pzim-devdata** [bahamas10/hueadm#15]
Hello,
Thank you for your API.
I'm trying to delete users and I have the following message : 
```
hueadm -H 192.168.1.XXX -U XXXXXXXXXXXXXXXX-XCXXXXXXXXXXXXX delete-user xxxxxxxx-xxxxxxxx-xxxxx-xxxx-xxxxxxxx
-
    error: {type: 1, address: /config/whitelist, description: 'unauthorized user'}

error: Error: unauthorized user
    at /usr/local/lib/node_modules/hueadm/lib/common.js:339:29
    at Array.forEach (<anonymous>)
    at finish (/usr/local/lib/node_modules/hueadm/lib/common.js:332:20)
    at /usr/local/lib/node_modules/hueadm/node_modules/hue-sdk/lib/hue.js:40:5
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/hueadm/node_modules/hue-sdk/lib/request.js:24:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 1,
  address: '/config/whitelist',
  _cmdlnInst: [CLI],
  _cmdlnSubcmd: 'delete-user',
  _cmdlnHandler: [Function]
}
```
I have tried this with two differents hue bridges and two differents users and I have always the same message.

Could you help me please ?

Thanks

**Comment by pzim-devdata** [comment]
I think it's because we can only delete **hueadm** users ? Can't we delete other users ?

**Comment by inverse** [comment]
Looks like that has to be done via https://account.meethue.com/
